name: ci

on: push

jobs:
    ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm i
            - name: Format files
              run: npm run fmt
            - name: Build application
              run: npm run build
            - name: Run tests
              run: npm run test
